//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Comments = new HashSet<Comment>();
            this.Reactions = new HashSet<Reaction>();
        }
    
        public int id { get; set; }
        public string news1 { get; set; }
        public string date { get; set; }
        public int categoryId { get; set; }
        public int userId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Reaction> Reactions { get; set; }
    }
}
